// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiu86YuLtEoFoZMq5Ey8dFNCStUwZCfhs',
    appId: '1:149515405359:web:5199fe8596882fed4ededa',
    messagingSenderId: '149515405359',
    projectId: 'ijob-pds',
    authDomain: 'ijob-pds.firebaseapp.com',
    storageBucket: 'ijob-pds.firebasestorage.app',
    measurementId: 'G-LRDB0DCXJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIumhxSd8S9t3tzHamXoZNdcPfwQwKpdw',
    appId: '1:149515405359:android:c7f80dfa20b1264a4ededa',
    messagingSenderId: '149515405359',
    projectId: 'ijob-pds',
    storageBucket: 'ijob-pds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_QMrPPc0Dh1lp8hwky99-SEQ7CClsFw',
    appId: '1:149515405359:ios:31a65d9679c297ca4ededa',
    messagingSenderId: '149515405359',
    projectId: 'ijob-pds',
    storageBucket: 'ijob-pds.firebasestorage.app',
    iosBundleId: 'com.example.ijobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF_QMrPPc0Dh1lp8hwky99-SEQ7CClsFw',
    appId: '1:149515405359:ios:31a65d9679c297ca4ededa',
    messagingSenderId: '149515405359',
    projectId: 'ijob-pds',
    storageBucket: 'ijob-pds.firebasestorage.app',
    iosBundleId: 'com.example.ijobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiu86YuLtEoFoZMq5Ey8dFNCStUwZCfhs',
    appId: '1:149515405359:web:97c6f54540c5948f4ededa',
    messagingSenderId: '149515405359',
    projectId: 'ijob-pds',
    authDomain: 'ijob-pds.firebaseapp.com',
    storageBucket: 'ijob-pds.firebasestorage.app',
    measurementId: 'G-218V60G89B',
  );

}